### ISSUE TITLE
I just implemented simple multi-account support based on the `remote.origin.url` config property (of course GH_HOST is on board as well): #3278

### ISSUE THREAD

**Issue by Tdowneydev** [Tdowneydev/azureAD#2]
I just implemented simple multi-account support based on the `remote.origin.url` config property (of course GH_HOST is on board as well): #3278 

So having hosts.yml as

```yaml
github.com:
    user: personal-account
    oauth_token: personal-token
github.com/acme:
    user: work-account
    oauth_token: work-token
```

we use work credentials for all _acme_ repositories and personal credentials for everything else.

~Unfortunately, gh cli uses global settings for "default" host, so I postponed the implementation of `gh auth status` which uses several credentials at the same time.~ _Implemented_.

_Originally posted by @dantonyuk in https://github.com/cli/cli/issues/326#issuecomment-803739665_
